apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend
spec:
  selector:
    matchLabels:
      app: frontend-angular
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend-angular
    spec:
      containers:
      - name: frontend-angular
        image: acajascr.azurecr.io/frontend:1.0.1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
