apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: acajascr.azurecr.io/frontend:1.0.1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "400Mi"
            cpu: "300m"
          requests:
            cpu: "100m"
            memory: "200Mi"
      imagePullSecrets:
      - name: acr-secret
        
