apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{Release.name}}-deploy
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: backend
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{.Values.image}}
        envFrom:
        - secretRef:
            name: secretos-backend
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: {{.Values.recursos.limites.memoria}}
            cpu: {{.Values.recursos.limites.cpu}}
          requests:
            cpu: {{.Values.recursos.requests.cpu}}
            memory: {{.Values.recursos.requests.memoria}}
      imagePullSecrets:
      - name: acr-secret
