apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: backend
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: acajascr.azurecr.io/backend:1.0.0-SNAPSHOT
        envFrom:
        - secretRef:
            name: secretos-backend
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "750Mi"
            cpu: "600m"
          requests:
            cpu: "200m"
            memory: "500Mi"
      imagePullSecrets:
      - name: acr-secret
