---
- name: Backup de base de datos PostgreSQL y subida a Azure Blob Storage
  hosts: localhost
  become: true
  vars:
    postgres_db: "acajasbd"
    postgres_user: "acajasbd"
    # local_backup_path: "/backups/{{ postgres_db }}-backup.sql.gz"
    postgres_password: "password"

  tasks:
    - name: Realizar dump de la base de datos PostgreSQL
      become: yes
      become_user: "{{ postgres_user }}"
      shell: pg_dump -U {{ postgres_user }} {{ postgres_db }} > /tmp/{{ postgres_db }}-backup.sql

    - name: Comprimir el archivo de volcado
      shell: gzip /tmp/{{ postgres_db }}-backup.sql

    # - name: Eliminar el archivo de backup local
    #   file:
    #     path: "/tmp/{{ postgres_db }}-backup.sql.gz"
    #     state: absent

    # - name: Verificar si el archivo de backup fue creado y cifrado
    #   stat:
    #     path: "{{ backup_file }}"
    #   register: backup_stat

    # - name: Comprobar si el backup fue exitoso
    #   fail:
    #     msg: "El archivo de backup no se creó correctamente."
    #   when: not backup_stat.stat.exists

    # - name: Crear carpeta de backups
    #   local_action:
    #     module: ansible.builtin.file
    #     path: "/backups"
    #     state: directory
    #     mode: '0777'

    # - name: Fetch del archivo de backup a la máquina local
    #   fetch:
    #     src: "{{ backup_file }}"
    #     dest: "{{ local_backup_path }}"
    #     flat: yes