---
- name: Descargar y restaurar base de datos PostgreSQL desde copia de seguridad
  hosts: localhost
  become: yes
  vars:
    backup_file: "/tmp/backup.sql.gz"
    db_name: "acajasbd"
    db_user: "acajasbd"

  tasks:
    - name: Copiar archivo a la m치quina remota
      ansible.builtin.copy:
        src: "{{ backup_file }}"
        dest: "{{ backup_file }}"
        mode: '0777'
  
    - name: "Restore the database"
      postgresql_db:
        state: restore
        name: "{{db_name}}"
        target: "{{backup_file}}"
      become: yes
      become_user: postgres

    - name: Verificar la restauraci칩n
      become: true
      shell: |
        psql -U {{ db_user }} -d {{ db_name }} -c "\dt"
      register: restore_check
      args:
        executable: /bin/bash

    - name: Eliminar el archivo de backup local
      file:
        path: "{{ backup_file }}"
        state: absent

    - name: Borrar directorio en la m치quina de control
      delegate_to: localhost
      ansible.builtin.command:
        cmd: rm -rf "{{ backup_file }}"

    - name: Mostrar resultado de la restauraci칩n
      debug:
        msg: "Tablas restauradas: {{ restore_check.stdout_lines }}"