- name: Instalar dependencias de python para hacer el backup
  hosts: [bd]
  become: true

  tasks:
    - name: Instalar dependencias necesarias
      become: true
      apt:
        name:
          - python3
          - python3-pip
          - python3-dev
          - python3-venv
          - libpq-dev
          - curl
        state: present