name: Insatalar a PostgreSQL en la máquina de la BD

on:
  workflow_dispatch:
    
jobs:
  ansible:
    runs-on: self-hosted
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Actualizar el sistema y preparar el entorno
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3.9-dev python3-venv libpq-dev
          python3 -m pip install --upgrade pip

      - name: Instalar Ansible
        run: |
          python3 -m pip install ansible

      - name: Verify Ansible Installation
        run: ansible --version

      - name: Instalar ssh
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Ejecutar playbook para instalar PostgreSQL
        run:  |
          cd ansible
          ansible-playbook -i inventory.ini postgresql.yml

      - name: Ejecutar playbook para hacer el backup
        run: |
          cd ansible
          ansible-playbook -i inventory.ini backup.yml
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}