name: Instalar a PostgreSQL en la máquina de la BD

on:
  workflow_dispatch:
    
jobs:
  ansible:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Instalar Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Verify Ansible Installation
        run: ansible --version

      - name: Instalar ssh
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Ejecutar playbook para instalar PostgreSQL
        run:  |
          cd ansible
          ansible-playbook -i inventory.ini postgresql.yml

      - name: Ejecutar playbook para hacer el backup
        run: |
          cd ansible
          ansible-playbook -i inventory.ini backup.yml
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}