name: Backup diario

on:
 schedule:
 - cron: '10 17 * * *'

jobs:
 backup:
  runs-on: self-hosted
  steps:
  - uses: actions/checkout@v3

  - name: Ejecutar playbook para hacer el backup
    run: |
      cd ansible
      ansible-playbook -i inventory.ini backup.yml
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}