name: Backup diario

on:
  workflow_dispatch:
#  schedule:
#  - cron: '40 15 * * *'

jobs:
 backup:
  runs-on: self-hosted
  steps:
  - uses: actions/checkout@v3

  - name: Crear archivo con la contraseña de Ansible
    run: |
      echo "$VAULT_PASSWORD" > vault_password.txt
    env:
      VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
    working-directory: ansible

  - name: Ejecutar playbook para hacer el backup
    run: |
      ansible-playbook -i inventory.ini backup.yml --vault-password-file vault_password.txt
    working-directory: ansible

  - name: Login az
    run: |
      az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}

  - name: Cifrar el archivo de volcado comprimido
    run: openssl enc -aes-256-cbc -salt -in /tmp/acajasbd-backup.sql.gz -out /tmp/acajasbd-backup.sql.gz.enc -k ${{ secrets.ENC_KEY }}

  - name: Subir backup
    run: |
      az storage blob upload --account-name staacajasdvfinlab --container-name backup --file /tmp/acajasbd-backup.sql.gz.enc --name acajasbd-backup.sql.gz.enc --overwrite

  - name: Eliminar archivos
    run: |
      sudo rm /tmp/acajasbd-backup.sql.gz.enc
      sudo rm /tmp/acajasbd-backup.sql.gz