name: Backup diario

on:
  workflow_dispatch:
#  schedule:
#  - cron: '40 15 * * *'

jobs:
 backup:
  runs-on: self-hosted
  steps:
  - uses: actions/checkout@v3

  - name: Ejecutar playbook para hacer el backup
    run: |
      cd ansible
      ansible-playbook -i inventory.ini backup.yml

  - name: Login az
    run: |
      az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}

  - name: Subir backup
    run: |
      az storage blob upload --account-name staacajasdvfinlab --container-name backup --file /tmp/acajasbd-backup.sql.gz --name acajasbd-backup.sql.gz --overwrite