name: Subir charts de Helm

on:
  workflow_dispatch:
    
jobs:
  subir:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup de Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.3

      - name: Comprimir charts
        run: |
          helm package backend/
          helm package frontend/
        working-directory: charts

      - name: Version del backend
        id: back_version
        run: |
          VERSION=$(grep "^version:" ./backend/Chart.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "back_version=$VERSION" >> $GITHUB_OUTPUT
        working-directory: charts

      - name: Version del frontend
        id: front_version
        run: |
          VERSION=$(grep "^version:" ./frontend/Chart.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "front_version=$VERSION" >> $GITHUB_OUTPUT
        working-directory: charts

      - name: Mostrar
        run: |
          echo "BACKEND: ${{steps.back_version.outputs.back_version}}"
          echo "FRONTEND: ${{steps.front_version.outputs.front_version}}"