name: Conectar cluster

on:
  workflow_dispatch:

jobs:
  cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar kubernetes
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Instalar az CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Instalar brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> $GITHUB_ENV

      - name: Instalar dependencias de brew
        run: |
          sudo apt-get install build-essential
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install gcc

      - name: Comprobar instalación de brew
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew --version

      - name: Instalar kubelogin
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install kubelogin

      - name: AZ Login
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}

      - name: AKS credentials
        run: |
          az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: AKS credentials
        run: |
          az aks get-credentials --resource-group final-project-common --name aksbootcampwe01 --overwrite-existing

      - name: AKS credentials
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          kubelogin convert-kubeconfig -l azurecli

      - name: Listar
        run: |
          sudo kubectl get deployments --namespace ns-acajas
