name: Disaster Recovery

on:
 workflow_dispatch:

jobs:
 dr:
  runs-on: self-hosted
  steps:
  - uses: actions/checkout@v3

  - name: Login az
    run: |
      az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}

  - name: Descargar el backup desde Azure utilizando la clave de la cuenta
    run: |
      az storage blob download --account-name staacajasdvfinlab -f /tmp/backup.sql.gz.enc -c backup -n acajasbd-backup.sql.gz.enc

  - name: Desencriptar el archivo
    run: openssl enc -d -aes-256-cbc -salt -in /tmp/backup.sql.gz.enc -out /tmp/backup.sql.gz -pass pass:${{ secrets.ENC_KEY }}

  - name: Ejecutar playbook para hacer el DR
    run: |
      cd ansible
      ansible-playbook -i inventory.ini dr.yml