name: Definir entornos

on:
 workflow_call:
  outputs:
    entorno:
      value: ${{ jobs.environment.outputs.environment }}
    desarrollo:
      value: ${{ jobs.environment.outputs.desarrollo }}
    rama:
      value: ${{ jobs.environment.outputs.rama }}

jobs:
 environment:
  runs-on: ubuntu-latest
  outputs:
   environment: ${{ steps.set_environment.outputs.environment }}
   desarrollo: ${{ steps.desarrollo.outputs.app_desarrollo }}
   rama: ${{ steps.branch.outputs.rama }}
  steps:
  - name: Checkout del repositorio
    uses: actions/checkout@v3

  - name: Definir rama
    id: branch
    run: |
      branch_name="${GITHUB_REF##*/}"
      echo "La rama es $branch_name"
      echo "rama=$branch_name" >> $GITHUB_OUTPUT

  - name: Definir entorno
    id: set_environment
    run: |
      if [[ "${{ steps.branch.outputs.rama }}" == *prod* ]]; then
        echo "environment=production" >> $GITHUB_OUTPUT
      else
        echo "environment=development" >> $GITHUB_OUTPUT
      fi

  - name: Extraer desarrollo
    id: desarrollo
    run: |
      REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)

      if [[ "$REPO_NAME" == *"backend"* && "${{ steps.set_environment.outputs.environment }}" == "production" ]]; then
        DESARROLLO="backend-production"
        echo "DESARROLLO=$DESARROLLO" >> $GITHUB_ENV
        echo "app_desarrollo=$DESARROLLO" >> $GITHUB_OUTPUT
      elif [[ "$REPO_NAME" == *"backend"* && "${{ steps.set_environment.outputs.environment }}" == "development" ]]; then
        DESARROLLO="backend-development"
        echo "DESARROLLO=$DESARROLLO" >> $GITHUB_ENV
        echo "app_desarrollo=$DESARROLLO" >> $GITHUB_OUTPUT
      fi

      if [[ "$REPO_NAME" == *"frontend"* && "${{ steps.set_environment.outputs.environment }}" == "production" ]]; then
        DESARROLLO="frontend-production"
        echo "DESARROLLO=$DESARROLLO" >> $GITHUB_ENV
        echo "app_desarrollo=$DESARROLLO" >> $GITHUB_OUTPUT
      elif [[ "$REPO_NAME" == *"frontend"* && "${{ steps.set_environment.outputs.environment }}" == "development" ]]; then
        DESARROLLO="frontend-development"
        echo "DESARROLLO=$DESARROLLO" >> $GITHUB_ENV
        echo "app_desarrollo=$DESARROLLO" >> $GITHUB_OUTPUT
      fi